export const countryCodeToName = {
  'AFG': 'Afghanistan',
  'ALB': 'Albania',
  'DZA': 'Algeria',
  'AGO': 'Angola',
  'ARG': 'Argentina',
  'ARM': 'Armenia',
  'AUS': 'Australia',
  'AUT': 'Austria',
  'BGD': 'Bangladesh',
  'BEL': 'Belgium',
  'BRA': 'Brazil',
  'KHM': 'Cambodia',
  'CMR': 'Cameroon',
  'CAN': 'Canada',
  'CHN': 'China',
  'COL': 'Colombia',
  'EGY': 'Egypt',
  'ETH': 'Ethiopia',
  'FRA': 'France',
  'DEU': 'Germany',
  'GHA': 'Ghana',
  'IND': 'India',
  'IDN': 'Indonesia',
  'IRN': 'Iran',
  'IRQ': 'Iraq',
  'ITA': 'Italy',
  'JPN': 'Japan',
  'KEN': 'Kenya',
  'MYS': 'Malaysia',
  'MEX': 'Mexico',
  'MAR': 'Morocco',
  'NPL': 'Nepal',
  'NLD': 'Netherlands',
  'NGA': 'Nigeria',
  'PAK': 'Pakistan',
  'PHL': 'Philippines',
  'POL': 'Poland',
  'RUS': 'Russia',
  'SAU': 'Saudi Arabia',
  'ZAF': 'South Africa',
  'KOR': 'South Korea',
  'ESP': 'Spain',
  'LKA': 'Sri Lanka',
  'SDN': 'Sudan',
  'SWE': 'Sweden',
  'CHE': 'Switzerland',
  'THA': 'Thailand',
  'TUR': 'Turkey',
  'GBR': 'United Kingdom',
  'USA': 'United States',
  'VNM': 'Vietnam',
  'YEM': 'Yemen',
  'ZMB': 'Zambia',
  'ZWE': 'Zimbabwe'
};

export const countryNameToCode = Object.entries(countryCodeToName).reduce((acc, [code, name]) => {
  acc[name] = code;
  return acc;
}, {}); 